name: py37
dependencies:
  - python=3.7
  - numpy
  - pandas
  - jupyter
  - ipython
  - scipy
  - sympy
  - scikit-learn
  - scikit-image
  - pillow
  - matplotlib
  - statsmodels
  - seaborn
  - pip:
    - tensorflow==2.0.0-alpha0
    - pymc3
    - jupyterlab
    - httpie
    - prompt-toolkit
    - cheat
    - scrapy
    - flask
    - flask-cors
    - requests
    - sphinx
    - sphinx_rtd_theme
    - psycopg2-binary
    - bpython
    - plotly
    - beautifulsoup4
    - mypy
    - pytest
    - pytest-cov
    - pylint
    - pydocstyle
    - pep8
    - pep8-naming
    - autopep8
    - doc8
    - flake8
    - flake8-comprehensions
    - flake8-bugbear
    - flake8-builtins
    - flake8-import-order
    - flake8-blind-except
